### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by andrewvmail** [TheFinestArtist/FinestWebView-Android#1]
Just wondering where would I integrate Google Analytics event code on a webviewfragment system. To track page view?

THANKS!

**Comment by adnbsr** [comment]
If you want to track events inside FinestWebViewActivity, you should customize from source code.

**Comment by TheFinestArtist** [comment]
@adnbsr Thanks for your answer. @andrewvmail I would recommend you to fork the project and customize it. Probably [onClick() method](https://github.com/TheFinestArtist/FinestWebView-Android/blob/master/library/src/main/java/com/thefinestartist/finestwebview/FinestWebViewActivity.java#L542) is right place to start :)
