### ISSUE TITLE
Fixed admob banner at footer?

### ISSUE THREAD

**Issue by punitm0** [TheFinestArtist/FinestWebView-Android#118]
How can I place a fixed admob banner at the footer of webview

**Comment by ponnamkarthik** [comment]
How you using the library

compile 'com.thefinestartist:finestwebview:1.2.7'

or 

download and importing the library ?

**Comment by ertcs** [comment]
Is there any option to use Interstitial or Banner Ad to use with webview? may be on back press or something like that or in footer?

**Comment by kksal55** [comment]
> Sabit bir admob afişini web görünümünün alt kısmına nasıl yerleştirebilirim?
Have you done the Admob settlement?

**Comment by kksal55** [comment]
> How can I place a fixed admob banner at the footer of webview

Have you done the Admob settlement?
