### ISSUE TITLE
How to add splash Screen

### ISSUE THREAD

**Issue by parmindersingh1** [TheFinestArtist/FinestWebView-Android#13]
hello sir,
I saw no option to add splash screen while webview load, how can i add splash screen

**Comment by TheFinestArtist** [comment]
@parmindersingh1 I will definitely add this feature!

**Comment by TheFinestArtist** [comment]
Hello @parmindersingh1, it would be great if you show me some design or concept of your splash page!

**Comment by parmindersingh1** [comment]
I didnt created any splash screen, i ant splash screen lile this in link
http://www.androidhive.info/2013/07/how-to-implement-android-splash-screen-2/

**Comment by TheFinestArtist** [comment]
@parmindersingh1 There is nice article about creation splash screen in Android.
http://www.androidhive.info/2013/07/how-to-implement-android-splash-screen-2/
https://www.bignerdranch.com/blog/splash-screens-the-right-way/

From Splash Screen, you can call FinestWebView as next Activity
