### ISSUE TITLE
Url is loading perfect in chrome but not in FinestWebView

### ISSUE THREAD

**Issue by pramodkr123** [TheFinestArtist/FinestWebView-Android#146]
Hi, 
My URL is showing perfectly in chrome browser but in FinestWebView, URL is not showing properly. It gets cut off half way. Bottom of the web page is not shown.

In FinestWebView
![fineastwebview](https://user-images.githubusercontent.com/37994302/39242678-8a057926-48a8-11e8-9feb-bbcc2f3d3654.png)

In Chrome
![chromebrowser](https://user-images.githubusercontent.com/37994302/39242292-2f8a7d94-48a7-11e8-8f41-5387645ccbf4.png)

Please tell me which flags to enable/disable to get full screen.

**Comment by TheFinestArtist** [comment]
I don't know what url you are using but I am suggesting to enable Javascript. Please reopen this issue when you still have problem after enabling Javascript.

**Comment by jimlyas** [comment]
this issue is still valid, and i'm currently had the same issue @TheFinestArtist
