### ISSUE TITLE
Alert Dialogs Crash Because WebView Uses Application Context Instead of Activity Context

### ISSUE THREAD

**Issue by makiftutuncu** [TheFinestArtist/FinestWebView-Android#18]
As explained in the title, when the page tries to create an AlertDialog as a selector when you click on a select element on the page, the application crashes. I did some digging and it is because at this line https://github.com/TheFinestArtist/FinestWebView-Android/blob/master/library/src/main/java/com/thefinestartist/finestwebview/FinestWebViewActivity.java#L406 you are using `getApplicationContext()` which brings the application level Context. WebView then is not able to add windows to it. I simply replaced it with `this` to refer the activity and the problem seems to be solved.

I'll post a PR if I have time.

Thanks.

**Comment by TheFinestArtist** [comment]
Fixed this issue and released new version [1.1.2](https://github.com/TheFinestArtist/FinestWebView-Android/releases/tag/1.1.2)
