### ISSUE TITLE
Check  com.nineoldandroids:library:2.4.0+

### ISSUE THREAD

**Issue by daimonkor** [TheFinestArtist/FinestWebView-Android#19]
Please help,

Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find any matches for com.nineoldandroids:library:2.4.0+ as no versions of com.nineoldandroids:library are available.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/nineoldandroids/library/maven-metadata.xml
>          https://jcenter.bintray.com/com/nineoldandroids/library/
>          http://dl.bintray.com/icebergteam/maven/com/nineoldandroids/library/maven-metadata.xml
>          http://dl.bintray.com/icebergteam/maven/com/nineoldandroids/library/
>          file:/C:/sdk/extras/android/m2repository/com/nineoldandroids/library/maven-metadata.xml
>          file:/C:/sdk/extras/android/m2repository/com/nineoldandroids/library/
>          file:/C:/sdk/extras/google/m2repository/com/nineoldandroids/library/maven-metadata.xml
>          file:/C:/sdk/extras/google/m2repository/com/nineoldandroids/library/
>      Required by:
>          project:app:unspecified > com.thefinestartist:finestwebview:1.0.8

**Comment by skram** [comment]
Remove the + at the end of 'com.nineoldandroids:library:2.4.0+', change it to 'com.nineoldandroids:library:2.4.0'. That fixed it for me.

**Comment by daimonkor** [comment]
Hm, but I use library as maven artifact  (compile at gradle), please fix

**Comment by Svenvollfied25** [comment]
Removing the + from the end didn't helped me. Please fix this problem.

**Comment by skram** [comment]
@daimonkor Anyone with a tutorial on compiling this as a Library to be imported manually to an Android Studio Project? I'd like to make some changes and import it that way.

**Comment by Svenvollfied25** [comment]
@skram Try this method.. I have tried it

http://stackoverflow.com/questions/27910140/how-to-compile-forked-library-in-gradle

**Comment by TheFinestArtist** [comment]
Fixed this issue and released new version [1.1.2](https://github.com/TheFinestArtist/FinestWebView-Android/releases/tag/1.1.2)
