### ISSUE TITLE
로딩완료후 화면이 깜빡거림

### ISSUE THREAD

**Issue by fofri** [TheFinestArtist/FinestWebView-Android#2]
로딩중에는 아래 리프레쉬 가 돌다가 멈추고 나면 화면이 깜빡 거립니다.  원인이 뭘까요?

안드로이드 공부하고 있는데  공부많이 했습니다. 감사합니다.

**Comment by TheFinestArtist** [comment]
@fofri 음...제가 라이브러리를 업데이트를 했는데 많이 바꿨습니다.

아마 화면이 깜빡거리는건 다양한 원인이 있을수 있는거 같은데, Google Chrome이나 다른 웹 어플에서도 같은 웹사이트 로딩시 깜빡거린다면 사이트 자체의 문제일수도 있는것이구.. 해당 웹사이트 url, device Android 버젼, device 정보 등등 주시면 확인해 보겠습니다!
