### ISSUE TITLE
Add constructor with context at Builder class

### ISSUE THREAD

**Issue by daimonkor** [TheFinestArtist/FinestWebView-Android#20]
I use global context (for get resources, drawable), please add constructor with Context param. Thanks.

**Comment by TheFinestArtist** [comment]
@daimonkor I can add this easily but If you add context then, the activity animation won't work!

**Comment by TheFinestArtist** [comment]
Look at this line: https://github.com/TheFinestArtist/FinestWebView-Android/blob/master/library/src/main/java/com/thefinestartist/finestwebview/FinestWebView.java#L851

If you still want to use `FinestWebView` without activity animation, I will add this feature!

**Comment by daimonkor** [comment]
I want use FinestWebView only as activity without animation). Your builder needed activity, but I see params with function from context, so I think that you can see replace activity to context and check instance of Activity class at show function.

**Comment by daimonkor** [comment]
Have you news about it?

**Comment by TheFinestArtist** [comment]
@daimonkor Wait for a second I will add this!

**Comment by TheFinestArtist** [comment]
@daimonkor Updated!

**Comment by daimonkor** [comment]
Thanks, I will test it.
