### ISSUE TITLE
If it is possible, please add an url listener

### ISSUE THREAD

**Issue by zunjae** [TheFinestArtist/FinestWebView-Android#22]
Using default WebView you can do this:

```
mWebView.setWebViewClient(new WebViewClient() {

   public void onPageFinished(WebView view, String url) {
        // do your stuff here
    }
});
```

Can you also implement this in FinestWebView if it's possible?

**Comment by TheFinestArtist** [comment]
@zunjae Added webview listeners
https://github.com/TheFinestArtist/FinestWebView-Android#webview-listeners
