### ISSUE TITLE
Custom widget and an activity

### ISSUE THREAD

**Issue by borolepratik** [TheFinestArtist/FinestWebView-Android#25]
Would you consider making a custom widget of the FinestWebView? That way, we can get the full control of the activity. I'm considering using this library, but i wont be able to add navigation drawer, other toolbar options, fragments, etc.

**Comment by TheFinestArtist** [comment]
Hi @borolepratik, I need full control of `Activity` to make some feature work. For example, `Refresh` menu need `toolbar` custom `layout` for menus and `webview`. I think I can make it as `Fragment` which is pretty challenging. But, I honestly think it's kind of hard to make `FinestWebView` as a custom widget. Sorry mate.
