### ISSUE TITLE
Attribute "rippleColor" has already been defined

### ISSUE THREAD

**Issue by appschris** [TheFinestArtist/FinestWebView-Android#34]
Conflicts with the support lib ! 

Please rename rippleColor to something else like _rippleColor !

Any help for this issue?

**Comment by TheFinestArtist** [comment]
Trying to find out where is the rippleColor is!

**Comment by TheFinestArtist** [comment]
@appsoluts Can you tell me which support library are you using including support library version.
You can also refer this issue from other library. https://github.com/mikepenz/MaterialDrawer/issues/379
I don't really see any conflicts when I tried to use `FinestWebView` with other support library!

Let me know if you keep having this issue!
