### ISSUE TITLE
Youtube background play

### ISSUE THREAD

**Issue by arsalanengr** [TheFinestArtist/FinestWebView-Android#40]
I have an issue in this library when i play any video and press home buttom the video will remain play on background this rejects my app from google play please help how can i fix it??

**Comment by DanteAndroid** [comment]
Try calling `webview.onPause()` in your activity's `onPause()`.

**Comment by TheFinestArtist** [comment]
@arsalkhan201241 Seriously, Google play rejects playing video on background?

**Comment by TheFinestArtist** [comment]
@arsalkhan201241 User `FinestWebView` version `1.2.3`. It automatically pause webview when the activity closes 👍

**Comment by arsalanengr** [comment]
I'll check it thanks :)
