### ISSUE TITLE
java.lang.NullPointerException: Call Base.initialize(context) within your Application onCreate() method.

### ISSUE THREAD

**Issue by rakshitsoni02** [TheFinestArtist/FinestWebView-Android#43]
please check this issue when pressing back button on chrome browser.

**Comment by rakshitsoni02** [comment]
please help me in this issue as this causes serious crash when coming on web view from other app.

**Comment by rakshitsoni02** [comment]
solved by adding Call Base.initialize(context)  in application class

**Comment by rokoroku** [comment]
I love this library, however, I suffered from the same issue after release. You'd better mention it on getting started section @TheFinestArtist .

**Comment by imidhuntv** [comment]
This bug still exists!! Please fix this!!

**Comment by imidhuntv** [comment]
Sorry, My bad. Adding the line  Base.initialize(this) in App.java solved it. Thank you @rakshitsoni02.

**Comment by justColbs** [comment]
`Base` does not exist when I try `import com.thefinestartist.Base;` Can't auto-import either.

Any idea why?
