### ISSUE TITLE
Invalid drawable tag Vector API 16

### ISSUE THREAD

**Issue by toneiv** [TheFinestArtist/FinestWebView-Android#48]
Hello

I've got an error with your library in API 16 : 
- My app is using vectors with the flag "vectorDrawables.useSupportLibrary = true"
- The error is about vector drawable : Binary XML file line #2: invalid drawable tag vector

I've managed to resolved it by editing the method updateIcon in the class FinestWebViewActivity.
Replace at line 853
`Drawable drawable = ContextCompat.getDrawable(this, drawableRes);
if (APILevel.require(21)) {
            VectorDrawable vectorDrawable = (VectorDrawable) drawable;
            vectorDrawable.setTintList(colorStateList);
            icon.setImageDrawable(vectorDrawable);
        } else {
            VectorDrawableCompat vectorDrawable = (VectorDrawableCompat) drawable;
            vectorDrawable.setTintList(colorStateList);
            icon.setImageDrawable(vectorDrawable);
        }`
by 
`VectorDrawableCompat vectorDrawable = VectorDrawableCompat.create(getResources(), drawableRes, null);
        vectorDrawable.setTintList(colorStateList);
        icon.setImageDrawable(vectorDrawable);`

Hope this helps

**Comment by TheFinestArtist** [comment]
Seems like the vector compat support API has been removed temporarily. https://code.google.com/p/android/issues/detail?id=205236

**Comment by TheFinestArtist** [comment]
I will update this library ASAP.

**Comment by TheFinestArtist** [comment]
Released 1.2.6 which doesn't uses any vector icons. I will reuse vector icons if Android support library is ready.
