### ISSUE TITLE
showUrl(false) not working

### ISSUE THREAD

**Issue by MohMah** [TheFinestArtist/FinestWebView-Android#5]
Hi, thanks for the awesome library! 
after calling .showUrl(false) it still shows the url below the title. 
and another thing that I wanted to have was that when using this with a Rtl language, dropdown menu items have left gravity and I think it would be great if you implement this into the builder to set the items gravity so it will work with Rtl languages.

**Comment by TheFinestArtist** [comment]
@MohMah Thank you for your report and suggestion. I will fix this issue ASAP.
1. `.showUrl(false)` not working.
2. dropdown menu gravity.

**Comment by TheFinestArtist** [comment]
@MohMah 
Just released `1.0.7` 4a106e6b0f93a78db70e1685f4bb691e2872058b.

Fixed `showUrl()` and added more options `menuTextGravity()`, `menuTextPaddingLeft()`, `menuTextPaddingRight ()`.

You might wanted to use just `rtl(true)` which will automatically reorder views from right to left. If the application supports rtl in manifest, you don't have to set rtl true in the builder.

**Comment by MohMah** [comment]
awesome, thanks! works like a charm
