### ISSUE TITLE
support for mailto: 

### ISSUE THREAD

**Issue by andrewjlow** [TheFinestArtist/FinestWebView-Android#63]
Hi @TheFinestArtist ,

First of all, thank you for developing this! I really appreciate it! :)

I noticed there is no check for `mailto:` for the `public boolean shouldOverrideUrlLoading(WebView view, String url)` method in the `MyWebClient`. Is it possible to add in support for this? Currently, clicking any `mailto:` link will give you the **net::ERR-UNKNOWN_URL_SCHEME** error page...

Thank you!

**Comment by kksal55** [comment]
@andrewjlow did you solve the problem?

**Comment by andrewjlow** [comment]
@kksal55 The latest version of the code now supports mailto.

**Comment by kksal55** [comment]
hi @andrewjlow I want to start instagram from within WebView (deep link)
I can do this with chrome. but I can not do it with FinestWebView
For example intent://instagram.com/_u/ebadgh/#Intent;package=com.instagram.android;scheme=https;end
