### ISSUE TITLE
WebView onPageFinished 

### ISSUE THREAD

**Issue by fncapps** [TheFinestArtist/FinestWebView-Android#8]
Hi, it would be useful if you could directly add code from the builder to the onPageFinished method of the webView. In my case I would need to inject some javascript and that way it would be really easy.

Thanks for the library man

**Comment by TheFinestArtist** [comment]
@fncapps Got it! I will find out which way is best to send callback from on activity to other!

**Comment by fncapps** [comment]
Great! I also made a pull request, nothing big, just translation

**Comment by TheFinestArtist** [comment]
@fncapps I just seen it! You can actually use `stringResRefresh` `stringResShareVia` etc for translation!

**Comment by TheFinestArtist** [comment]
@fncapps Can you tell me what kind of javascript you want inject? or Can you give me some code samples? I don't really know where to start..

**Comment by TheFinestArtist** [comment]
@fncapps I think I did it, but I don't know whether I named the method properly or whether this is what you are looking for! Added 'injectJavaScript(String javaScript)` method.

**Comment by fncapps** [comment]
I've taken a look to the code, that should work! Thanks!

**Comment by TheFinestArtist** [comment]
@fncapps If you need some changes, please let me know or give me any pull request!
